ALTER TABLE EVENTOS ADD (
	CONSTRAINT EVE_CK_CAT CHECK (CATEGORIA_EVENTO IN ('SE'/*SEMINARIO*/,'AS'/*ASAMBLEA*/,'CO'/*CONVENCIONE*/,'JO'/*JORNADA*/,'CG'/*CONGRESO*/,'RE'/*REUNIONE*/,'CF'/*CONFERENCIA*/,'SI'/*SIMPOSIO*/,'TA'/*TALLER*/,'FO'/*FORO*/,'CU'/*CURSO*/))
);