ALTER TABLE ESTABLECIMIENTOS ADD (
	CONSTRAINT EST_FK_IDLU FOREIGN KEY (ID_LUGAR) REFERENCES LUGARES (ID_LUGAR),
	CONSTRAINT EST_CK_ACR CHECK (ACREDITACION IN ('A'/*ALTA*/)),
	CONSTRAINT EST_CK_TIPE CHECK (TIPO_ESTABLECIMIENTO IN ('UN'/*UNIVERSIDAD*/,'EM'/*EMPRESA*/,'IN'/*INSTITUTOS*/,'OT'/*OTRO*/))
);