ALTER TABLE LUGARES ADD (
	CONSTRAINT LUG_FK_IDU FOREIGN KEY (ID_UBICACION) REFERENCES LUGARES (ID_LUGAR),
	CONSTRAINT LUG_CK_TIPOL CHECK (TIPO_LUGAR IN ('D'/*DEPARTAMENTO*/,'M'/*MUNICIPIO*/,'O'/*OTRO*/))
);
