ALTER TABLE PUBLICACIONES ADD (	
	CONSTRAINT PUB_FK_IDFUN FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO),
	CONSTRAINT PUB_FK_IDEM FOREIGN KEY (ID_EMPLEO) REFERENCES EMPLEOS (ID_EMPLEO),
	CONSTRAINT PUB_FK_IDEV FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS (ID_EVENTO),
	CONSTRAINT PUB_FK_IDRE FOREIGN KEY (ID_REVISTA) REFERENCES REVISTAS (ID_REVISTA),
	CONSTRAINT PUB_FK_IDLU FOREIGN KEY (ID_LUGAR) REFERENCES LUGARES (ID_LUGAR),
	CONSTRAINT PUB_CK_TIPOP CHECK (TIPO_PUBLICACION IN ('RE'/*REVISTA*/,'EM'/*EMPLEO*/,'EV'/*EVENTO*/))
	
);