-- Creación de las condiciones de la tabla ASUNTOS
-- Creado por: Deybi Jordan Pulido Robles 
-- Fecha de creación: 08/04/2016
-- Modificado por:
-- Fecha de modificación:
-- Observaciones:

ALTER TABLE ASUNTOS ADD (
	CONSTRAINT ASU_FK_IDLU FOREIGN KEY (ID_LUGAR) REFERENCES LUGARES (ID_LUGAR),
	CONSTRAINT ASU_FK_IDES FOREIGN KEY (ID_ESTABLECIMIENTO) REFERENCES ESTABLECIMIENTOS (ID_ESTABLECIMIENTO),
	CONSTRAINT ASU_CK_TIPASU CHECK (TIPO_ASUNTO IN ('RE'/*REVISTA*/,'EM'/*EMPLEO*/,'EV'/*EVENTO*/)),
	CONSTRAINT ASU_CK_TIPCAT CHECK (TIPO_CATEGORIA IN ('SE'/*SEMINARIO*/,'AS'/*ASAMBLEA*/,'CO'/*CONVENCIONE*/,'JO'/*JORNADA*/,'CG'/*CONGRESO*/,'RE'/*REUNIONE*/,'CF'/*CONFERENCIA*/,'SI'/*SIMPOSIO*/,'TA'/*TALLER*/,'FO'/*FORO*/,'CU'/*CURSO*/)),
	CONSTRAINT ASU_CK_TIPCON CHECK (TIPO_CONTRATO IN ('TF'/*TERMINO_FIJO*/,'TI'/*TERMINO_INDEFINIDO*/,'CO'/*CONTRATO_OCACIONAL*/))
);
