INSERT INTO `establecimientos`(`NOMBRE_ESTABLECIMIENTO`, `TIPO_ESTABLECIMIENTO`, `ACREDITACION`) VALUES ("UNIVERSIDAD PEDAGÓGICA Y TECNOLÓGICA DE COLOMBIA",'UN',"Alta calidad");
INSERT INTO `establecimientos`(`NOMBRE_ESTABLECIMIENTO`, `TIPO_ESTABLECIMIENTO`, `ACREDITACION`) VALUES ("SENA",'IN',null);
INSERT INTO `establecimientos`(`NOMBRE_ESTABLECIMIENTO`, `TIPO_ESTABLECIMIENTO`, `ACREDITACION`) VALUES ("SANTO TOMAS",'UN',null);
INSERT INTO `establecimientos`(`NOMBRE_ESTABLECIMIENTO`, `TIPO_ESTABLECIMIENTO`, `ACREDITACION`) VALUES ("JUAN DE CASTELLANOS",'UN',null);
INSERT INTO `establecimientos`(`NOMBRE_ESTABLECIMIENTO`, `TIPO_ESTABLECIMIENTO`, `ACREDITACION`) VALUES ("UNIBOYACA",'UN',null);