INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (1,14);
INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (1,1);
INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (1,2);
INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (1,5);

INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (2,2);
INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (2,1);
INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (2,6);
INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (2,18);

INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (3,5);

INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (4,15);
INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (4,9);

INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (5,11);
INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (5,16);
INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (5,13);
INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (5,6);

INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (6,2);

INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (7,2);
INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (8,2);
INSERT INTO `grupos`(`ID_ASUNTO`, `ID_AREA`) VALUES (9,2);